import { describe, expect, it, vi } from "vitest";
import { apiFetchJson } from "./client";
import { chatCacheKey, normalizeChatReply, sendChatMessage } from "./chat";
vi.mock("./client", () => ({ apiFetchJson: vi.fn() }));

describe("governed chat contract", () => {
  it("normalizes absent envelope arrays", () => { const reply = normalizeChatReply({ status: "empty", tenant_id: "motoshop", text: "No encontré registros.", conversation_id: "c1", turn_count: 1, tools_used: [] }); expect(reply.status).toBe("empty"); expect(reply.sources).toEqual([]); expect(reply.freshness).toEqual([]); expect(reply.entity_refs).toEqual([]); expect(reply.attachments).toEqual([]); });
  it("isolates tenant/user/conversation cache keys", () => { expect(chatCacheKey("motoshop", "ana", "c1")).not.toBe(chatCacheKey("masvital", "ana", "c1")); expect(chatCacheKey("motoshop", "ana", "c1")).not.toBe(chatCacheKey("motoshop", "bruno", "c1")); });
  it("preserves evidence, links, freshness, and expired attachments", async () => { vi.mocked(apiFetchJson).mockResolvedValueOnce({ status: "partial", tenant_id: "motoshop", text: "Ventas disponibles.", conversation_id: "c1", turn_count: 2, tools_used: ["sales"], sources: [{ source_id: "s1", domain: "sales", kind: "duckdb", citation: "Ventas", cutoff_at: "2026-09-13", observed_at: "2026-09-15T10:00:00Z", status: "used" }], freshness: [{ domain: "sales", cutoff_at: "2026-09-13", observed_at: "2026-09-15T10:00:00Z", status: "current" }], entity_refs: [{ entity_type: "product", entity_id: "SKU-1", label: "Filtro", domain: "inventory", href: "/inventario/productos/SKU-1" }], attachments: [{ type: "report", format: "pdf", filename: "ventas.pdf", download_url: "/api/reports/download/r1", state: "expired", expires_at: "2026-09-14T10:00:00Z", date_from: null, date_to: null, period_label: "Septiembre" }] }); const reply = await sendChatMessage("ventas", "c1", "r1"); expect(reply.sources[0]?.citation).toBe("Ventas"); expect(reply.freshness[0]?.status).toBe("current"); expect(reply.entity_refs[0]?.href).toBe("/inventario/productos/SKU-1"); expect(reply.attachments[0]?.state).toBe("expired"); expect(vi.mocked(apiFetchJson)).toHaveBeenCalledWith("/api/llm/qa/chat", expect.objectContaining({ body: JSON.stringify({ message: "ventas", conversation_id: "c1", request_id: "r1" }) })); });
});
